AndelaOSP/wirebot

- .gitignore
- index.js
- modules/actions.js
- modules/messages.js
- Defines the incident reporting bot workflow
- Users can log incidents via slack
- Log in to wire-factory and interact with the bot.
https://www.pivotaltracker.com/story/show/151797578
> #151797578 log incident

- index.js
- modules/validation/description_validation.js
This PR validates the description of an incident entered on Slack, bot-side
- When a user enters a description of the incident being reported, the bot should ask them to repeat if it is less than 10 words
Given that you are signed in to a Slack workspace where the bot has been installed:
- Initiate a conversation with the bot
- Respond to the bot's initial prompts, up until it prompts you to describe what happened
- Type in a description
- If the description is less than 10 words, the bot will prompt you to be more descriptive
This will help gather a clear understanding of the incident being reported as the description will be adequately descriptive
[#152106987](https://www.pivotaltracker.com/n/projects/2117172/stories/152106987)
> #152106987 Validate Description of Incident Entered

- README.md
This PR updates the project's `README`
- This PR updates the project's `README` to provide vital information to stakeholders about the project
As a user, when I access the project's repository on Github:
- I should see a detailed `README` of the project
This will provide vital information to stakeholders about the project, including setting up and installation, running the bot locally and testing new branches and pull requests
N/A
[#155808773](https://www.pivotaltracker.com/n/projects/2117172/stories/155808773)
> #155808773 Update Project Readme

- package.json
This PR moves `nodemon` from `dependencies` to `devDependencies` and updates the `engines` config option to accommodate more `node versions` in `package.json`
- Move `nodemon` from `dependencies` to `devDependencies` in `package.json`
- Update `engines` config option to accommodate more node versions in `package.json`
- Nodemon is a dev utility and should therefore be listed under `devDependencies` in package.json 
- The update to the `engines` config will allow devs/contributors with node versions from as low as v6.9.0 to be able to contribute to the project
[#155951337](https://www.pivotaltracker.com/n/projects/2117172/stories/155951337)
> #155951337 Cleanup Package.json

- .eslintrc.js
- .eslintrc.json
- index.js
- modules/actions.js
- modules/messages.js
- modules/validation/date_validation.js
- modules/validation/description_validation.js
- modules/validation/location_validation.js
- modules/validation/subject_validation.js
- modules/validation/witnesses_validation.js
- package.json
- yarn.lock
- Run `yarn lint:fix` to see results
> Setup eslint

- index.js
- modules/actions.js
- modules/levels.js
- modules/messages.js
- modules/validation/location_validation.js
This PR posts an incident to the API when it's submitted via the `Slack bot`
- When an incident is reported using the `Slack bot`, the incident's details are posted to the API and consequently created on the backend
Given that you are signed in to a Slack workspace where the bot has been installed:
- Initiate a conversation with the bot
- Indicate that you want to report an incident
- Proceed through the steps of reporting an incident
- Confirm and submit the incident
- Confirm on the `backend` that the incident has been created
This will allow for the creation of reported incidents on the backend, whose data can then be used for other applications such as the frontend
N/A
[#153113987](https://www.pivotaltracker.com/n/projects/2117172/stories/153113987)
> #153113987 Post Incident to API

- yarn.lock
This PR fixes the `Heroku build fail error` due to conflicting `yarn.lock` files
[#156320370](https://www.pivotaltracker.com/n/projects/2117172/stories/156320370)
> #156320370 Fix Heroku Deploy Error

- yarn.lock
- Release v1.0.0
[Delivers #156320370]
> v1.0.0 release

- .env.example
- index.js
- modules/location_centres.js
- package.json
- yarn.lock
This PR adds a cron job for POSTing Slack members to the API
Members of predefined Slack channels will automatically be POSTed to the API every Monday at 22:00 hrs by the cron job
This will aid in creating new members of the aforementioned channels to the DB on a regular automated basis
N/A
[#156818646](https://www.pivotaltracker.com/n/projects/2117172/stories/156818646)
> #156818646 Add Cron Job

- index.js
This PR adds a notification to a predefined Slack channel when the cron job is done running
When the cron job is done running:
- A notification will be sent to the predefined developer team's `monitoring` channel indicating the cron job is completed
This will help the developer team in keeping track and monitoring the cron job
[#157245819](https://www.pivotaltracker.com/n/projects/2117172/stories/157245819)
[Delivers #157245819]
> #157245819 Slack Notification when Cron Job Done

- .circleci/config.yml
- .circleci/deploy.sh
- .dockerignore
- Dockerfile
This PR adds CI pipeline to build and deploy the bot to k8s cluster once the PR has been merged to staging or master.
With the current implementation, the deployment process has been automated. This means when a release is merged to staging and master, the ci will build a Docker image, publish it to GCP container registry and update the k8s cluster with the recent image.
Finishes [#157938965](https://www.pivotaltracker.com/story/show/157938965)
> Prepare Bot for docker builds and deployment.

- .editorconfig
- .eslintrc.json
- .gitignore
- README.md
- package-lock.json
- package.json
- test/acceptance/slack-events.spec.js
- test/helpers/index.js
- test/index.spec.js
- test/unit/validation.spec.js
Setup the testing framework for Wirebot.
- _Testing framework_
- `Acceptance`
- Tentative - BDD - mocha - chai - should - mocks.
- `Unit`
-  mocha - chai - expect
- `integration`
- N/A
1. Setup the test framework using `mocha`, `chai`, `nyc`.
2. Setup test helpers
3. Create the test folders `Acceptance`, `Unit`.
4. Create Dummy acceptance and unit tests.
5. add a test command to package.json.
- run the command `npm test` on the project locally
#157862372 Setup Testing for Wirebot
> Chore #157862372 Setup testing for Wirebot 

- .circleci/config.yml
Setup Continuous Integration with CircleCI for Wirebot.
CircleCI should run tests for all branches but run deployment only for the `master` and `staging` branch.
1. Add test command to the Circleci config.
- After PR is merged.
- Visit the CircleCI dashboard for Wirebot and see that tests run for new pull-requests.
#158082602 Setup Continuous Integration with CircleCI
> Chore #158082602: Setup Continuous Integration with CircleCI.

- .circleci/config.yml
- .codeclimate.yml
- package.json
Setup code coverage for Wirebot.
Codeclimate code coverage tool used.
1. Add code coverage command to the Circleci config.
- After PR is merged.
- New PR's should run code coverage tests when created.
#158184673 Setup Code Coverage
> Chore #158184673 :  Setup code coverage for Wirebot

- .eslintrc.json
- index.js
- modules/actions.js
- modules/incident_handler_verification.js
- modules/location_centres.js
- modules/messages.js
- modules/post_pnc_members.js
This PR displays a drop-down for selecting the location an incident took place
Given a user is reporting a new incident:
- The bot will display a drop-down for selecting where the incident occurred, with `the various centres` and `Other` as options 
- If the user selects `one of the centres`, the location will be saved and they can proceed with the other steps of reporting the incident
- Else, if the user selects `Other`, they will be requested to manually key in the location in the format `Place, City, Country`. After this, they will be presented with another drop-down to select where the `incident should be handled`, with the `various centres` as options
Initiate the process of reporting an incident via the bot and proceed. The drop-down(s) will be displayed at the appropriate step(s). …
> #158112427 Incident Location Drop-down

- .circleci/config.yml
- .circleci/deploy.sh
- .codeclimate.yml
- .dockerignore
- .editorconfig
- .eslintrc.json
- .gitignore
- Dockerfile
- README.md
- index.js
- modules/actions.js
- modules/incident_handler_verification.js
- modules/location_centres.js
- modules/messages.js
- modules/post_pnc_members.js
- package-lock.json
- package.json
- test/acceptance/slack-events.spec.js
- test/helpers/index.js
- test/index.spec.js
- test/unit/validation.spec.js
> v1.2.0 release

- logs/index.js
- modules/middlewares.js
- modules/services.js
- modules/slack/interactive_messages.js
- modules/slack/messages.js
- modules/utils.js
- package.json
- test/helpers/stubs.js
- test/index.spec.js
- test/unit/middlewares.spec.js
- test/unit/utils.spec.js
- test/unit/wirebot.spec.js
- wirebot.js
Minor Fixes from refactoring the wirebot codebase.
- fix missing Kampala UG from the list
- fix require description (15 characters)
- Change prompt: `Which Andela P&C team should handle this?`, to `Which Andela People team should handle this?`. Also fix the place holder.
- Date validation - Accept only past dates.
- fix `clear witnesses` button
- fix re-submission after validation
#158583916 Refactor Wirebot
> ft(refactor): minor fixes

- logs/index.js
- modules/middlewares.js
- modules/services.js
- modules/slack/interactive_messages.js
- modules/slack/messages.js
- modules/slack/web_client.js
- modules/utils.js
- package.json
- test/helpers/index.js
- test/helpers/stubs.js
- test/index.spec.js
- test/unit/services.spec.js
- test/unit/utils.spec.js
- test/unit/wirebot.spec.js
- wirebot.js
Minor Fixes from refactoring the wirebot codebase.
- fix missing Kampala UG from the list
- fix require description (15 characters)
- Change prompt: `Which Andela P&C team should handle this?`, to `Which Andela People team should handle this?`. Also fix the place holder.
- Date validation - Accept only past dates.
- fix `clear witnesses` button
- fix re-submission after validation
#158583916 Refactor Wirebot
> ft(refactor): minor fixes 2

- modules/slack/messages.js
This PR refactors the frontend URL of the created incident
Once an incident has been created and a notification posted on the respective People Slack channel, clicking `View Incident on Wire` should open the incident on `Wire frontend`
- Use the bot to report an incident
- Once the incident has been successfully created, a Slack notification should be sent to the respective People Slack channel
- Click on `View Incident on Wire`
- The specific incident should be opened on Wire frontend
N/A
[#160130114](https://www.pivotaltracker.com/n/projects/2117172/stories/160130114)
> #160130114 Refactor Created Incident Frontend URL

- modules/services.js
- modules/slack/messages.js
- modules/utils.js
- Update front end URL
- Include slackId's in API responses
> Upgrade to match with API changes
